services:
  soundproc:
    build: .
    image: soundproc
    user: anon
    volumes:
      - type: bind
        source: ./src
        target: /home/anon/src
      - type: volume
        source: virtualenvs
        target: /home/anon/.local/share/virtualenvs

volumes:
  virtualenvs:
